"""Unique Medium-severity click-paths. Imported by build_issues.py."""

MEDIUM_STEPS = {
    5: [
        "Go to Settings → Checkout. Abandoned checkout emails are here (and in Shopify Email / Automations) — not in the theme.",
        "Open a recent abandoned checkout under Orders → Abandoned checkouts. Tap the recovery link yourself in incognito.",
        "If the link 404s, the checkout expired or the customer already completed it. Send a new recovery from that abandoned checkout.",
        "Marketing → Automations (or Shopify Email): confirm the abandoned-cart flow is On and the button URL is the Shopify recovery link, not a homepage.",
        "Place a test cart, wait for the email, open it on your phone. Copy these steps to a friend if the link still dies.",
    ],
    6: [
        "Go to Discounts. Open the code that should have applied.",
        "Check combinations: if it cannot combine with product discounts, an automatic deal is blocking it.",
        "Customer, minimum purchase, usage limit, and sales channel must all match. A POS-only code will not work on the online store.",
        "Incognito checkout with a new customer email. Old accounts often already used a once-per-customer code.",
        "Do not paste discount logic into Liquid. Fix it on the discount, then retry.",
    ],
    9: [
        "Go to Settings → Shipping and delivery → Local pickup.",
        "Each pickup location must be enabled, with hours, and that location must have Available stock — On hand in another warehouse does not count.",
        "Products → Inventory: the fulfilling location for pickup must track quantity.",
        "Draft order: choose that pickup location and the customer's postal code. If pickup vanishes, the location is excluded from the delivery profile.",
        "Test on the storefront in incognito. Copy the location name if you ask a friend.",
    ],
    12: [
        "Open the product. It must be a Digital product (or have no shipping required) for the download to send.",
        "Files live on the product → media / digital files. A 404 download means the file was removed or never attached.",
        "Settings → Notifications: the order confirmation / digital download email must be On.",
        "Fulfillment: digital items auto-fulfill only if that setting is on. Manual fulfill if the email never sent.",
        "Place a $1 test, complete payment, open the email on a phone. Do not put download URLs in theme.liquid.",
    ],
    13: [
        "Go to Products → Gift cards. Open the card whose balance looks wrong.",
        "Partial redemptions write a new remaining balance on the gift card — not on the order note.",
        "If a manual balance edit will not save, you are not the store owner or the card is disabled.",
        "Checkout test: apply the code, pay the remainder, then reopen the gift card. The new balance should match.",
        "Do not Edit code to 'force' a balance. Copy the last four of the code to a friend — never the full code in chat.",
    ],
    18: [
        "Go to Settings → Payments and open the fraud-filter / blocking app.",
        "Corporate cards and +alias emails often trip 'high risk' rules. Find the rule that matched the declined order Timeline.",
        "Allowlist the company domain if you truly want those orders — do not turn every filter off.",
        "Disable the fraud app once and retry a $1 order. If it goes through, the app is the block, not Shopify Payments.",
        "Re-enable with a narrower rule. Copy the rule name, not customer card numbers.",
    ],
    19: [
        "Go to Settings → Checkout. Address autocomplete is Shopify + Google — not your theme's map pin.",
        "If a country/region format is rejected, turn off strict address verification for that market or add the region in Shipping zones.",
        "Test the same address in a draft order. If draft saves but checkout rejects, a checkout app is rewriting the address.",
        "Customize → App embeds: disable address-validator apps and retry.",
        "Do not paste a Google Maps key into theme.liquid on the live shop.",
    ],
    21: [
        "Online Store → Themes → Duplicate first. Do not Edit code on the published theme.",
        "Customize the copy → product / cart template. Shop Pay, Apple Pay, and Google Pay buttons are checkout settings plus the theme's payment-button block.",
        "Settings → Payments: express methods must be on. A missing button is often Payments, not CSS.",
        "Preview mobile width. If buttons jump, a custom CSS app or extra PayPal button is stacking. Disable one embed.",
        "Publish the copy only when Preview on a phone looks stable.",
    ],
    23: [
        "Cart notes / attributes must be enabled in Settings → Checkout (or the cart form in Customize).",
        "If the note vanishes on the order, an app is stripping cart attributes at checkout. Disable the newest checkout app embed.",
        "Draft order: add a note, complete checkout in incognito, open the order. The note should sit on the order, not only in the cart drawer.",
        "Do not add a hidden Liquid input on the live theme to 'save' notes.",
        "Copy the missing note text from the cart screenshot if you ask a friend.",
    ],
    26: [
        "Go to Settings → Customer accounts. If accounts are required, guests cannot finish checkout.",
        "Classic vs new customer accounts both can loop if 'login to checkout' is on and the login page errors.",
        "Try guest checkout in incognito. If it works, the customer is stuck on a login/password reset, not payments.",
        "Disable required login temporarily to confirm. Then fix the login page (passwordless email, not Edit code).",
        "Staff logins cannot complete customer checkout. Use a real customer test account.",
    ],
    29: [
        "Go to Settings → Languages (and Markets). Checkout language follows the market/locale, not a theme translate filter.",
        "Publish the language and add checkout translations in Translate & Adapt (or Shopify's checkout editor).",
        "If fields snap back to English, the market's default language is English — switch the market language or the domain.",
        "Do not paste translated checkout.liquid. Checkout extensibility + Translate & Adapt only.",
        "Incognito to that market domain and read the pay button. Copy these steps to a friend.",
    ],
    33: [
        "Online Store → Themes → Duplicate the live theme. Do not Edit code on the published theme.",
        "Customize the copy. Preview at a phone width. Note which section overlaps (header, product grid, cart).",
        "Turn off the newest app embed (menus, popups, chat). Overlaps are usually an extra overlay, not 'broken CSS'.",
        "If a custom CSS app injected max-width rules, disable it on the copy and Preview again.",
        "Publish the copy only when a real phone looks right. Never paste a forum CSS reset into the live shop.",
    ],
    35: [
        "Online Store → Themes → Duplicate first.",
        "Product images jumping are missing width/height or a gallery app fighting the theme.",
        "Customize the copy → product media. Use Shopify image settings; turn off a second gallery/zoom app.",
        "Compress huge PNGs (Products → media). 4000px files stutter on phones.",
        "Preview the product on mobile. Publish the copy only.",
    ],
    37: [
        "Online Store → Navigation. Open the menu that drops children.",
        "Nested items must hang under the parent in the menu editor — not only in the theme.",
        "Duplicate the theme. Customize → header. Mega-menu apps plus the theme mega-menu = dropped children. Leave one.",
        "Preview desktop hover and mobile tap. Do not Edit code to 'force' dropdowns on live.",
        "Publish the copy when both work.",
    ],
    38: [
        "Online Store → Themes → Duplicate. Do not minify the live theme by hand.",
        "Online Store → Themes → … → Edit code only on the copy if you must — first disable extra apps. Each app adds CSS/JS.",
        "Settings → Apps: remove unused apps so their scripts stop loading.",
        "Theme settings / speed: enable native lazy-loading; do not stack three speed apps.",
        "Preview, then publish the copy. Copy these steps if a friend is chasing TTFB.",
    ],
    39: [
        "Settings → Search & Discovery (or Apps → Search & Discovery). Filters are not collection tags in the theme anymore.",
        "The collection must be available to the Online Store channel and use the Search & Discovery filter group.",
        "If filters do not refresh, a collection-filter app is fighting the native one. Disable the app embed.",
        "Duplicate the theme before touching collection JSON templates.",
        "Test the collection in incognito. Publish only the copy.",
    ],
    43: [
        "Open the product → Variants. Each color needs a swatch (variant image or native swatch category).",
        "Blank circles mean the swatch image/hex is empty, or the option name is not 'Color'.",
        "Search & Discovery → swatches: map the option. Do not paint circles in theme CSS on live.",
        "Duplicate the theme if a swatch app is installed — two swatch systems hide each other.",
        "Preview the product, tap each color, confirm the image changes.",
    ],
    45: [
        "Online Store → Themes → Duplicate. Infinite scroll is a theme or app script, not Shopify core.",
        "Customize the copy → collection. Turn off infinite scroll and use pagination, or disable the extra infinite-scroll app.",
        "Two scroll scripts freeze the page. One at a time.",
        "Test the 2nd page of the collection in incognito.",
        "Publish the copy. Do not paste a jQuery infinite-scroll snippet into the live theme.",
    ],
    46: [
        "Duplicate the theme. Quick view is an app or theme feature — not checkout.",
        "Customize → App embeds: disable the newest quick-view / popup app.",
        "If the close button fails, a second modal (newsletter, chat, age gate) is trapping focus. Disable that too.",
        "Preview a collection on mobile. Open and close quick view twice.",
        "Publish the copy only.",
    ],
    47: [
        "Stop. Shopify strips scripts from Custom Liquid in some sections on purpose.",
        "Online Store → Themes → Duplicate. Put allowed embeds in App embeds or Custom Liquid that Shopify still permits — never in the live published theme first.",
        "iframes and third-party scripts belong in an app embed, not a Custom Liquid dump.",
        "If you need a pixel, Settings → Customer events — not theme.liquid.",
        "Preview the copy. Roll back if the section blanks.",
    ],
    50: [
        "The header cart count is theme JS plus the cart object. Duplicate the theme first.",
        "If count stays 0, a cart-drawer app is not updating the header, or two cart scripts race.",
        "Customize → App embeds: one cart app only. Preview add-to-cart.",
        "Incognito (old service workers cache a broken cart.js).",
        "Publish the copy when the bubble matches the cart.",
    ],
    54: [
        "Settings → Search & Discovery → Predictive search. Turn it on and include products/collections.",
        "If a search app (Algolia, Klevu) is installed, native predictive search will look empty. Use one engine.",
        "Duplicate the theme before removing search JS. Disable the extra search embed first.",
        "Type 3 letters on the storefront in incognito.",
        "Do not paste a custom autocomplete script into the live header.",
    ],
    55: [
        "Product videos: use Shopify-hosted video or one embed (YouTube or Vimeo), not both plus a theme player.",
        "Duplicate the theme. Customize → product media. Disable a second video/zoom app.",
        "Autoplay + muted is required on mobile. If it interrupts, turn off autoplay on the copy.",
        "Preview on iPhone. Publish the copy only.",
        "Do not paste extra YouTube iframe code into product descriptions on top of the media gallery.",
    ],
    57: [
        "Online Store → Themes → Duplicate. Custom CSS in the editor leaks when a selector is missing a closing brace.",
        "Customize the copy → the section → Custom CSS. Remove the last CSS you pasted. Save.",
        "Do not put store-wide CSS in a single section box.",
        "If an app injects CSS, disable that embed.",
        "Preview, then publish the copy. Never paste CSS into the live theme.liquid.",
    ],
    58: [
        "Review stars breaking the layout are a review app embed, not the product description.",
        "Duplicate the theme. Customize → App embeds: one review app (Judge.me, Loox, Yotpo). Two will overlap.",
        "Put the widget in the product section Shopify provides, not a raw HTML dump.",
        "Preview mobile. Publish the copy.",
        "Do not Edit code to float stars on the live shop.",
    ],
    65: [
        "Open the product. Changing the handle changes the URL. Shopify can create a redirect — confirm it.",
        "Online Store → Navigation → URL redirects. Add old-handle → new product URL if it is missing.",
        "Do not leave two products with the same handle. The leftover 404s.",
        "Test the old URL in incognito. You should land on the product, not a loop.",
        "Do not add redirects in Liquid.",
    ],
    66: [
        "Open the smart collection. Conditions are AND/OR — a product must match the rule you think it does.",
        "Tags are case-sensitive and must be saved on the product. A trailing space in a tag drops it.",
        "If you recently renamed a tag, update the collection rule to the new tag.",
        "Manual collections do not auto-add. Switch to automated or add the product by hand.",
        "View the collection storefront in incognito after Save.",
    ],
    67: [
        "The bulk editor times out on thousands of rows. Select fewer products (one collection or a search).",
        "Products → Export, edit in Google Sheets, then Import those columns only (price, inventory).",
        "Do not keep retrying the same 5,000-row bulk edit — you will double-change some rows.",
        "Work as the store owner. Some staff permissions cannot bulk-edit.",
        "A 10-row test import first, then the rest.",
    ],
    69: [
        "Open the product. Physical products need a weight > 0 or carrier rates disappear.",
        "Set weight and unit on every variant, not only the parent.",
        "Settings → Shipping: the profile that includes this product must still have a rate.",
        "Draft order with the customer's postal code. If rates appear, the storefront was missing weight.",
        "CSV: Variant Grams must be a number. Do not Edit code.",
    ],
    71: [
        "Settings → Custom data → Metafields. Open the definition. Type (number, JSON, list) must match what you paste.",
        "A text string in a number field will not save. Change the value or the definition — not both at once.",
        "Product metafields are on the product; variant metafields are on the variant. Wrong place looks like 'it vanished'.",
        "Do not output the metafield in Liquid on the live theme until the value saves in admin.",
        "Save, reload the product, confirm the value is still there.",
    ],
    72: [
        "Open the product. Status Draft vs Active vs Scheduled is the publish switch — not the theme.",
        "Sales channels: tick Online Store (and others). An Active product hidden from Online Store will 404.",
        "Scheduled publish needs a future date. If it stayed draft, the schedule never ran — set Active now.",
        "Markets: the product must be included in that market.",
        "Incognito the product URL after Save.",
    ],
    74: [
        "Open variants. Two SKUs that look alike ('ABC-1' vs 'ABC–1') confuse warehouses even if Shopify allows them.",
        "Search products for the SKU. Rename duplicates. Empty SKU is OK; colliding SKUs are not.",
        "CSV imports often copy the same SKU down. Fix the sheet, re-import those rows.",
        "POS barcode scan uses SKU/barcode — keep them unique.",
        "Save. Fulfill a test order and read the SKU on the slip.",
    ],
    76: [
        "Open the product. Compare-at price must be higher than price or the sale badge math looks broken.",
        "Clear compare-at if you are not on sale. A lower compare-at confuses Markets and some feeds.",
        "Check every variant — one leftover compare-at flags the whole product as sale.",
        "Do not calculate discounts in Liquid to hide this.",
        "View the product storefront in incognito.",
    ],
    77: [
        "Product media: upload one image at a time if a 4K batch hangs.",
        "Resize over ~20MB files before upload. Shopify will fail the whole batch on one giant video.",
        "Wait for the spinner. Re-upload only the failed file, not the whole gallery.",
        "Do not paste image URLs into theme.liquid to skip the media library.",
        "When the gallery shows in admin, Preview the product.",
    ],
    80: [
        "Open the product. Tax is Settings → Taxes plus the product's 'charge tax' checkbox.",
        "Tax-exempt collections do not exist as a magic tag unless you set a tax override on those products.",
        "B2B company tax exempt is on the company, not the product.",
        "Do not hide tax in the theme. Checkout will still charge it.",
        "Draft order to that region and read the tax line.",
    ],
    82: [
        "Open the product. Preorder is continue-selling + a message, or a preorder app — pick one.",
        "Inventory policy: Continue selling when out of stock. Add a theme block or metafield for the ship date — on a duplicate theme.",
        "A tag named preorder does nothing by itself unless a collection/app looks for it.",
        "Do not promise a date in Liquid that inventory cannot meet.",
        "Test add-to-cart at quantity 0. Copy the ship-date text to a friend.",
    ],
    83: [
        "Shopify allows 3 options (e.g. Size, Color, Material). A 4th option needs a split product or a line-item property.",
        "Do not install an 'unlimited options' app and expect checkout, shipping, and POS to stay simple.",
        "Split the product (e.g. by material) or use a personalization field for engraving.",
        "Stay under 100 variants total.",
        "Save, then add to cart in incognito.",
    ],
    86: [
        "Go to Discounts → create an automatic Buy X get Y (or open your GWP app).",
        "The free item must have stock at the fulfilling location and be included in the sales channel.",
        "Stacking: another automatic discount may block GWP. Check combinations.",
        "Incognito: add the trigger product, confirm the gift appears in the cart before checkout.",
        "Do not add the gift in theme JS. Checkout will not charge or track it correctly.",
    ],
    88: [
        "Personalization (engraving) is a line-item property on the product form, or a custom-options app.",
        "Duplicate the theme before adding a property field. Do not Edit code on live.",
        "After checkout, the text must appear on the order line. If it dies, the app is not passing properties.",
        "Disable a second options app. One only.",
        "Place a $1 test with sample text, open the order. Copy these steps to a friend.",
    ],
    89: [
        "Products → Inventory → Transfers. Open the stuck transfer.",
        "Receive it at the destination location. 'Pending' forever usually means nobody tapped Receive.",
        "Origin must have the stock. You cannot ship what that location does not have On hand.",
        "If an ERP creates transfers, reconnect that app (see integrations) instead of duplicating in admin.",
        "After Receive, Available at the destination should rise. Do not Edit code.",
    ],
    96: [
        "Open Zapier (or Make). The Shopify connection often expires — Reconnect.",
        "Check the Zap history for the failed order. A 400 usually means a missing field (SKU, email).",
        "Do not fire the same order to two Zaps that both create tickets — you will double-process.",
        "Shopify → Settings → Notifications webhooks are separate from Zapier. Use one path per job.",
        "Replay one order, confirm the other app received it.",
    ],
    98: [
        "Open Yotpo / Loox / Judge.me. Reconnect Shopify if reviews vanished after a product handle change.",
        "The widget is an app embed. Duplicate the theme, enable one review embed, disable extras.",
        "Product must match by handle or SKU in the review app. A new product URL orphans old reviews.",
        "Do not paste a second review script into product.liquid on live.",
        "Preview the product. Publish the copy.",
    ],
    99: [
        "Affiliate cookies die on Shop Pay / PayPal sometimes — that is the affiliate app, not your theme.",
        "Open the affiliate app. Check the last click and whether the order used an express wallet.",
        "Allow the affiliate script in Customer privacy (marketing). A blocked cookie cannot credit.",
        "Do not add a second affiliate pixel in theme.liquid.",
        "Run a test order with the affiliate link in incognito, then a normal checkout, and compare credit.",
    ],
    100: [
        "Open Printful / Printify. Holds are usually missing print files or a size that does not match the mockup.",
        "Re-push the order from the POD app. Check the variant mapping (SKU ↔ print file).",
        "Shopify fulfillment stays 'unfulfilled' until the POD accepts it — do not also fulfill by hand or you will double-ship.",
        "Artwork: PNG/PDF at their required DPI. A tiny logo triggers a hold.",
        "Fix the file, resubmit one order, then the queue.",
    ],
    101: [
        "Open HubSpot / Salesforce. Reconnect the Shopify connector.",
        "Phone fields fail when Shopify stores +1 and the CRM expects digits only (or the reverse).",
        "Turn off two-way phone sync if each edit overwrites the other system.",
        "Sync one customer. Confirm the CRM ID. Do not map 20 fields at once.",
        "This is not a theme issue.",
    ],
    103: [
        "Open Smile.io / Yotpo Loyalty. Points miss custom/draft orders unless that event is enabled.",
        "Reconnect Shopify. Enable Placed Order and the POS channel if you sell in person.",
        "Refunds should claw back points — check the loyalty log, not the theme.",
        "Do not calculate points in Liquid.",
        "Place a test order, confirm points on the customer, then refund and confirm the clawback.",
    ],
    107: [
        "Wholesale signup is a page + a form app or B2B company request — not a theme contact form unless you built it that way.",
        "Check the form app's notifications. If admin never gets the email, the form failed to submit (required field / captcha).",
        "Customers → Companies: approve the request. Pending companies cannot see wholesale prices.",
        "Duplicate the theme before changing the form. Do not Edit code on live.",
        "Submit a test application with a unique email.",
    ],
    110: [
        "Post-purchase upsell apps can break currency or Shop Pay. Open that app first.",
        "Disable the upsell embed and run a $1 checkout. If currency is correct, the upsell app is the culprit.",
        "Markets currency + upsell apps often disagree. Turn off the upsell on secondary markets.",
        "Do not stack two upsell apps.",
        "Re-enable one market, test once, then the rest.",
    ],
    114: [
        "B2B catalogs hide retail prices for company contacts — not for guests.",
        "Customers → Companies → catalog. Assign the catalog. Guest visitors will still see retail. That is expected.",
        "If logged-in wholesale still sees retail, the contact is not linked to the company.",
        "A B2B login app fighting Shopify B2B will show both prices. Use one.",
        "Incognito: guest vs company contact. Copy both screenshots to a friend.",
    ],
    115: [
        "Algolia / Klevu empty results usually mean the index is rebuilding or credentials expired.",
        "Open the search app → reindex. Wait. Do not also enable Shopify predictive search at the same time.",
        "Duplicate the theme. One search embed only.",
        "Type a SKU you know exists. If native search finds it and the app does not, the app index is stale.",
        "Do not paste a new search script into the live header.",
    ],
    118: [
        "Open Loop / Returnly / your returns app. The portal link is in that app, not in Shopify Shipping.",
        "Reconnect Shopify. A failed label is usually address, carrier account, or prepaid label credits.",
        "The order must be fulfilled before most return portals will print a label.",
        "Do not paste a returns URL into theme.liquid; use the app's customer account block on a duplicate theme.",
        "Run a test return on a $1 order.",
    ],
    119: [
        "A/B testing apps inject extra CSS and cause flicker. Duplicate the theme first.",
        "Customize → App embeds: pause the A/B app. If flicker dies, keep tests off the checkout and header.",
        "Do not run two A/B tools.",
        "Preview without the app, then with one experiment only.",
        "Publish the stable copy. Never paste experiment JS into live theme.liquid.",
    ],
    120: [
        "On the POS device: Shopify POS app → Settings → Connected tools.",
        "Forget the Bluetooth scanner, toggle Bluetooth, pair again. Firmware updates happen in the POS app / reader settings, not in admin Liquid.",
        "The location in POS must match admin. A mismatch looks like 'scanner does nothing'.",
        "Test scan a barcode that exists as a variant barcode (not only SKU) into the cart.",
        "If it still fails, swap the scanner before changing checkout settings.",
    ],
    123: [
        "Google Search Console errors on product schema are usually missing price/availability or a theme JSON-LD app fighting Shopify's default.",
        "Duplicate the theme. Disable extra SEO/schema apps so only one JSON-LD block remains.",
        "Products need a price, image, and availability. Empty compare-at or hidden price breaks rich results.",
        "Do not paste schema from a blog into the live product template.",
        "Re-test the product URL in Google's rich results tool after Preview.",
    ],
    125: [
        "Shopify rebuilds sitemap.xml automatically. New products can take hours to appear — do not paste a custom sitemap in Liquid.",
        "The product must be Active and available to Online Store. Drafts never enter the sitemap.",
        "Online Store → Preferences: confirm the domain Search Console is using is the primary storefront domain.",
        "In Search Console, inspect the product URL. Request indexing after the product is truly live.",
        "Do not block /sitemap in robots. Copy the product URL to a friend.",
    ],
    128: [
        "Go to Settings → Customer privacy. Cookie banner must actually block marketing cookies until accept.",
        "Two privacy apps = broken banner. Keep Shopify privacy + one CMP, or just Shopify.",
        "Pixels in Customer events should respect consent. Pixels pasted in theme.liquid will not.",
        "Duplicate the theme and remove leftover cookie snippets from the copy.",
        "Test EU-style deny vs accept in incognito. Publish the copy.",
    ],
    130: [
        "Go to Settings → Billing. A past-due Shopify or app invoice can lock features — pay it there.",
        "App charges are separate from Shopify Payments payouts. The right screen is Billing, not Payments.",
        "If a charge looks wrong, cancel the app or contact the app vendor. Do not rotate cards in a loop.",
        "Store owner email gets the invoice. Staff may not see Billing.",
        "This is not a theme issue. Copy the invoice number to a friend.",
    ],
    132: [
        "Settings → Languages / Markets. hreflang is emitted by Shopify for published languages and market domains.",
        "Each language must be published. A translated theme string is not enough.",
        "Do not paste a hreflang snippet into theme.liquid — you will duplicate Shopify's tags and confuse Google.",
        "Primary domain + market subfolders/domains must match what Search Console expects.",
        "View page source on two market URLs and confirm one hreflang set. Duplicate the theme if an SEO app adds a second set, then disable that app.",
    ],
    136: [
        "Settings → Billing / Shopify Capital. Daily remittance is a percent of sales — it will not match a single payout 1:1.",
        "Compare Capital deductions on the payout Timeline, not on the bank statement alone.",
        "If the percent looks wrong, it is Capital / Shopify — not the theme and not a tax setting.",
        "Do not 'fix' this by changing Markets rounding.",
        "Download the payout CSV and copy the Capital line to a friend or accountant.",
    ],
    138: [
        "Duplicate product URLs: pick one canonical product and redirect the other handle.",
        "Online Store → Navigation → URL redirects. Point extras at the main product.",
        "Collections should not also list a second product URL for the same SKU.",
        "SEO apps that rewrite canonicals can fight Shopify. Disable extras.",
        "Do not paste canonical link tags into the live theme.liquid.",
    ],
    143: [
        "Customers → Export. Huge lists time out in the browser. Filter (e.g. one tag) or use Shopify's emailed export.",
        "Do not keep clicking Export. You will queue duplicates.",
        "Work as store owner. Some staff cannot export PII.",
        "If you need more than Shopify will email, use a customer-export app, not a theme hack.",
        "Open the CSV in Google Sheets. Copy these steps to a friend.",
    ],
    145: [
        "Online Store → Themes → Duplicate the live theme before any code or app install. That duplicate is the backup.",
        "Download a theme zip from the theme menu if you need an offline copy.",
        "Shopify does not keep every keystroke. If you already edited live, duplicate whatever is left now and stop.",
        "Roll back by publishing an older unpublished theme — not by pasting from chat.",
        "Never Edit code on the published theme again.",
    ],
    146: [
        "Settings → Users and permissions. Remove the staff account.",
        "Settings → Apps → Develop apps / collaborator apps: revoke API tokens that staff created.",
        "Collaborators from Partner accounts are removed in Users as well.",
        "A leftover custom app token can still write products after the person is gone. Rotate it.",
        "Do not share the owner login to 'replace' staff.",
    ],
    147: [
        "Settings → Apps → Develop apps → Create an app. You need the store owner.",
        "Scopes: only what the job needs. Missing write_products is why 'it will not save'.",
        "Install the app on this store after you set scopes. An uninstalled custom app has no token.",
        "Never paste Client secret into Storescope, chat, or the theme.",
        "If the token is already in chat, revoke it and create a new one.",
    ],
    149: [
        "Go to Settings → Markets → the market → rounding / pricing.",
        "Checkout cents that differ from the product page are market rounding or include/exclude tax — not a theme formatter.",
        "Turn off rounding or set it to the same rule on every market.",
        "Do not round prices in Liquid. Cart and checkout will disagree.",
        "Preview that market, add to cart, read the checkout total. Copy both numbers to a friend.",
    ],
}
